<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-31T19:05:48 IST" name="Default suite" finished-at="2023-08-31T19:06:02 IST" duration-ms="14352">
    <groups>
    </groups>
    <test started-at="2023-08-31T19:05:48 IST" name="Default test" finished-at="2023-08-31T19:06:02 IST" duration-ms="14352">
      <class name="vtigerFinalScripts.CreateEventTest">
        <test-method is-config="true" signature="classSetup()[pri:0, instance:vtigerFinalScripts.CreateEventTest@31ea9581]" started-at="2023-08-31T19:05:48 IST" name="classSetup" finished-at="2023-08-31T19:05:50 IST" duration-ms="1843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetup -->
        <test-method is-config="true" signature="methodSetup()[pri:0, instance:vtigerFinalScripts.CreateEventTest@31ea9581]" started-at="2023-08-31T19:05:50 IST" name="methodSetup" finished-at="2023-08-31T19:05:55 IST" duration-ms="5159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetup -->
        <test-method signature="createEventTest()[pri:0, instance:vtigerFinalScripts.CreateEventTest@31ea9581]" started-at="2023-08-31T19:05:55 IST" name="createEventTest" finished-at="2023-08-31T19:06:00 IST" duration-ms="4842" status="FAIL">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: "10/18/25"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: "10/18/25"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at pompages.CreateNewEventPage.chooserequiredDate(CreateNewEventPage.java:48)
at vtigerFinalScripts.CreateEventTest.createEventTest(CreateEventTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEventTest -->
        <test-method is-config="true" signature="methodTearDown()[pri:0, instance:vtigerFinalScripts.CreateEventTest@31ea9581]" started-at="2023-08-31T19:06:00 IST" name="methodTearDown" finished-at="2023-08-31T19:06:02 IST" duration-ms="1912" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
        <test-method is-config="true" signature="classTearDown()[pri:0, instance:vtigerFinalScripts.CreateEventTest@31ea9581]" started-at="2023-08-31T19:06:02 IST" name="classTearDown" finished-at="2023-08-31T19:06:02 IST" duration-ms="546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTearDown -->
      </class> <!-- vtigerFinalScripts.CreateEventTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
